
server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_registration
    username: GraceGh
    password: Carl
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
